apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cc-tech-newgrad-f-frontend-dev
  namespace: cc-tech-newgrad-f
  name: cc-tech-newgrad-f-frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cc-tech-newgrad-f-frontend-dev
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: cc-tech-newgrad-f-frontend-dev
    spec:
      containers:
        - name: cc-tech-newgrad-f-frontend-dev
          image: teamf-frontend-image
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            runAsUser: 101
            runAsGroup: 101
      serviceAccountName: tenant-pod-default
      automountServiceAccountToken: true # Istio sidecar needs to communicate with k8s API
