apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gfp-frontend-{{APP_ENV}}
  namespace: ecbs-gfp-frontend
  name: gfp-frontend-{{APP_ENV}}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: gfp-frontend-{{APP_ENV}}
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: gfp-frontend-{{APP_ENV}}
        version: v1
        networkpolicy.ecbs-bos.rakuten/network-policy: allow
      annotations:
        sla: high
        tier: application
        role: frontend-ui
    spec:
      securityContext:
        runAsUser: 999
      volumes:
        - name: log-storage
          emptyDir: {}
        - name: podinfo
          downwardAPI:
            items:
              - path: labels
                fieldRef:
                  fieldPath: metadata.labels
              - path: annotations
                fieldRef:
                  fieldPath: metadata.annotations
      imagePullSecrets:
        - name: harbor-bot
      containers:
        - name: gfp-frontend-{{APP_ENV}}
          env:
            - name: TZ
              value: "Asia/Tokyo"
          image: gfp-frontend-image
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 1Gi
