apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: teamf-frontend-dev
  namespace: teamf-frontend-dev
  name: teamf-frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: teamf-frontend-dev
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: teamf-frontend-dev
    spec:
      containers:
        - name: teamf-frontend-dev
          image: teamf-frontend-image
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            runAsUser: 101
            runAsGroup: 101
      serviceAccountName: tenant-pod-default
      automountServiceAccountToken: true # Istio sidecar needs to communicate with k8s API
